### ISSUE TITLE
Vertical offset in GBC Virtual Console games with TGA

### ISSUE THREAD

**Issue by leo60228** [ChainSwordCS/CHokiMod#4]
All GBC Virtual Console games I've tested look like this with TGA:
![image](https://github.com/ChainSwordCS/ChirunoMod/assets/8355305/28dcddb3-fd9e-40e3-b56d-89381806b2f4)

The offset doesn't seem to change while a game is started, but seems like it might shift slightly between restarts. It doesn't happen when not using TGA. I've tried both stable and nightly builds on a New 3DS XL.

**Comment by ChainSwordCS** [comment]
I've replicated the issue, and I'm looking into it.

![1](https://github.com/ChainSwordCS/ChirunoMod/assets/72537076/e9d778ac-df5c-4bb8-a563-2c55d942ead1)
![2](https://github.com/ChainSwordCS/ChirunoMod/assets/72537076/01823d64-ca06-44dd-952a-9f8fb2990a50)

I think it's an issue with Chokistream. I'll try to upload test builds with the bugfix soon

**Comment by Eiim** [comment]
btw, this is fixed in the targa-rewrite branch of Chokistream, which will be included in a stable release sometime soonish.
