### ISSUE TITLE
ChirunoMod fails to start, DMA transfer not finished stopping manually...

### ISSUE THREAD

**Issue by woody188** [ChainSwordCS/CHokiMod#6]
Running on O3DSXL, I open the ChirunoMod Himem script via the installed cia, but it just drops back to the main menu as suspended software. If I open ChirunoMod via the normal cia script, it does work, even though it's supposed to be the Himem version to use with the O3DSXL.

Looking in the HzLog.log on root, it says repeating:

DMA transfer not finished stopping manually...
dmaState=-1031164

Looks like maybe this has been an issue in the past. This was in the search cache, but I couldn't find the same text on the site currently:
![image](https://github.com/ChainSwordCS/ChirunoMod/assets/24919359/88566b67-1649-49cf-b196-89950f71b586)

**Steps taken**
Tried older versions of ChirunoMod and both scripts. None seem to work with the Himem script.

**Versions/settings**
ChirunoMod 0.2.2 (and tried 0.2.1)
Luma3DS v13.0.2

**Comment by ChainSwordCS** [comment]
Based on the description, I don't think this is a bug.

The HIMEM loader works a bit differently than the regular loader:
1. Launch the HIMEM loader.
2. It should send you back to the Home Menu, with the loader currently Suspended.
3. **You should now launch the game you want to play, and press A when it asks "Close the suspended software and launch this one?"**
4. The game should load normally, with ChirunoMod running in the background.

Also, just in case you didn't already know: you only need to use the HIMEM loader if you're trying to play a game which runs in Extended Memory Mode on o3DS. Only a few specific games are like this; Super Smash Bros, Super Mario Maker for 3DS, Pokemon Sun / Moon / Ultra Sun / Ultra Moon, and maybe a few others (unfortunately I can't find a complete list...)

Feel free to let me know if this fixed it, or if you're still having any issues!
