### ISSUE TITLE
ChirunoMod_experimental_o3ds.cia viewer?

### ISSUE THREAD

**Issue by maverickdfz** [ChainSwordCS/CHokiMod#7]
Chokistream does not work with the method that the experimental o3ds file uses

[ChirunoMod_experimental_o3ds.cia](https://github.com/ChainSwordCS/ChirunoMod/blob/nightly-v4/ChirunoMod_experimental_o3ds.cia)

Is there a viewer that works with this?

**Comment by ChainSwordCS** [comment]
Try using the latest nightly or the most recent [stable release](https://github.com/ChainSwordCS/ChirunoMod/releases). They should work with old-3DS.

That specific build was very outdated, and most likely not what you really want anyway. (It was just a broken experimental feature.) I just removed it, and at the same time made sure all the real nightly builds are up to date. And to answer your question more directly, it probably worked with an older version of Chokistream (assuming it worked at all).
