### ISSUE TITLE
I get an odd error when trying to connect to my 3ds please help.

### ISSUE THREAD

**Issue by pug1234** [ChainSwordCS/CHokiMod#8]
![image](https://github.com/ChainSwordCS/ChirunoMod/assets/78324670/661d12b7-f561-403b-95e4-98b7fe36a569)

**Comment by pug1234** [comment]
when i ping the 3ds i get
![image](https://github.com/ChainSwordCS/ChirunoMod/assets/78324670/4a5dd5d0-3752-4999-a6fc-82c4bc9fd6e3)

**Comment by pug1234** [comment]
however I get an error with ChirunoMOD

**Comment by pug1234** [comment]
settings are as follows
![image](https://github.com/ChainSwordCS/ChirunoMod/assets/78324670/708da540-11de-4ebc-8fb8-7452e0f799fa)

**Comment by Eiim** [comment]
Try restarting the 3DS and re-opening ChirunoMod, then attempting to reconnect.

**Comment by pug1234** [comment]
ok ill try that

**Comment by pug1234** [comment]
still get
![image](https://github.com/ChainSwordCS/ChirunoMod/assets/78324670/addb070f-a95e-4d67-a63e-e3543312e156)

**Comment by Eiim** [comment]
> however I get an error with ChirunoMOD

What do you mean by this?

**Comment by pug1234** [comment]
I try to connect to it from my pc and it gives a java error.

**Comment by pug1234** [comment]
on my computer

**Comment by Eiim** [comment]
Does connecting to other mods from ChirunoMod work?

**Comment by pug1234** [comment]
it's always after I hit connect and it doesn't even pop up the display.

**Comment by pug1234** [comment]
no

**Comment by pug1234** [comment]
they don't work for me either

**Comment by pug1234** [comment]
they all give the same error

**Comment by pug1234** [comment]
here is the application folder on the PC end
![image](https://github.com/ChainSwordCS/ChirunoMod/assets/78324670/1219801e-f8c6-44c2-8884-f9c970029d21)

**Comment by pug1234** [comment]
am I missing something?

**Comment by Eiim** [comment]
Alright, so if it's not a ChirunoMod-specific issue, that definitely helps eliminate some possibilities. It's almost certainly a networking issue of some kind. Potentially an over-eager firewall blocking certain ports? Or the IP you have is wrong (a different device on the network). I would suggest you connect to a different mod with a different software (eg. Snickerstream). If that doesn't work, then it's a network issue on your end and there's not really anything we can do for you.

**Comment by pug1234** [comment]
thanks for trying. :)

**Comment by pug1234** [comment]
solved I had the wrong yet similarly named CIA file on my old 3ds.

**Comment by pug1234** [comment]
solved
